const {
    cryptoNews,
    expressUk,
    economicTimes,
    theSun,
    financeMagnates,
    thetimes,
    jamaicaobserver,
    gulftoday,
    ksusentinel,
    investing,
    investopedia,
    morningstar,
    stockhead,
    cityam,
    bloombergquint,
    cointelegraph,
    equitybulls,
    outlookindia,
    coindesk,
    digitaljournal,
    cyprusMail,
    menafn,
    startuptipsdaily,
    fxempire,
    govinfosecurity,
    thisismoney,
    investmentu,
    nairametrics,
    benzinga,
    nasdaq,
    forbes,
    cnbc,
    moneycontrol,
    leadership,
    politico,
    fxmag,
    coinjournal,
    investorplace,
    livemint,
    venturebeat,
    gizmodo,
    ibtimes,
    albawaba,
    inc42,
    marketwatch,
    etfdailynews,
    independent,
    mybroadband,
    gulfnews,
    euronews,
    channelnewsasia,
    finder,
    vulcanpost,
    wsj,
    timesofindia,
    nypost,
    reuters,
    businesswire,
    smh,
    cnn,
    bbc

} = require('./helperNewsFunctions');



module.exports.newsSource = {
    'https://cryptonews.com': cryptoNews,
    'https://express.co.uk/finance': expressUk,
    'https://economictimes.indiatimes.com': economicTimes,
    'https://thesun.co.uk': theSun,
    'https://financemagnates.com': financeMagnates,
    'https://thetimes.co.uk/search?source=nav-desktop&q=crypto': thetimes,
    'https://jamaicaobserver.com/business': jamaicaobserver,
    'https://gulftoday.ae/business': gulftoday,
    'https://ksusentinel.com': ksusentinel,
    'https://investing.com': investing,
    'https://investopedia.com/markets-news-4427704': investopedia,
    'https://morningstar.com': morningstar,
    'https://stockhead.com.au': stockhead,
    'https://cityam.com/crypto': cityam,
    'https://bloombergquint.com/markets': bloombergquint,
    'https://cointelegraph.com': cointelegraph,
    'https://equitybulls.com': equitybulls,
    'https://outlookindia.com': outlookindia,
    'https://coindesk.com': coindesk,
    'https://digitaljournal.com/?s=crypto': digitaljournal,
    'https://cyprus-mail.com': cyprusMail,
    'https://menafn.com': menafn,
    'https://startuptipsdaily.com': startuptipsdaily,
    'https://fxempire.com/crypto': fxempire,
    'https://govinfosecurity.com': govinfosecurity,
    'https://thisismoney.co.uk': thisismoney,
    'https://investmentu.com': investmentu,
    'https://nairametrics.com': nairametrics,
    'https://benzinga.com': benzinga,
    'https://www.nasdaq.com/market-activity/cryptocurrency': nasdaq,
    'https://forbes.com/crypto-blockchain': forbes,
    'https://cnbc.com': cnbc,
    'https://moneycontrol.com': moneycontrol,
    'https://leadership.ng': leadership,
    'https://politico.eu': politico,
    'https://fxmag.com': fxmag,
    'https://coinjournal.net': coinjournal,
    'https://investorplace.com': investorplace,
    'https://livemint.com': livemint,
    'https://venturebeat.com': venturebeat,
    'https://gizmodo.com': gizmodo,
    'https://ibtimes.com': ibtimes,
    'https://albawaba.com': albawaba,
    'https://inc42.com': inc42,
    'https://marketwatch.com': marketwatch,
    'https://etfdailynews.com': etfdailynews,
    'https://independent.co.uk/news/business': independent,
    'https://mybroadband.co.za': mybroadband,
    'https://gulfnews.com': gulfnews,
    'https://euronews.com': euronews,
    'https://channelnewsasia.com': channelnewsasia,
    'https://finder.com.au': finder,
    'https://vulcanpost.com': vulcanpost,
    'https://wsj.com': wsj,
    'https://timesofindia.indiatimes.com': timesofindia,
    'https://nypost.com': nypost,
    'https://reuters.com': reuters,
    'https://businesswire.com': businesswire,
    'https://smh.com.au': smh,
    'https://edition.cnn.com/business': cnn,



}